# Generated by Django 4.2.3 on 2023-07-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp_creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
